### ISSUE TITLE
About the `spglib` interface used in `SpaceGroupIrep`.

### ISSUE THREAD

**Issue by hongyi-zhao** [goodluck1982/SpaceGroupIrep#13]
The [`spglib`](http://spglib.github.io/spglib/) tool supplies many interfaces, as described on its official website: Spglib is a library for finding and handling crystal symmetries written in C. There are the [python](http://spglib.github.io/spglib/python-spglib.html#python-spglib), [fortran, rust, and ruby](http://spglib.github.io/spglib/interface.html#interfaces) interfaces.

Based on the inspection of `SpaceGroupIrep` source code and the concise description in the paper [Comput. Phys. Commun. 265 , 107993 (2021)](https://doi.org/10.1016/j.cpc.2021.107993) as shown below, I confirmed that the python interface is used in this package.
```shell
$ rg '\b(import spglib|from spglib import) '
getBCsymmetry.py
13:import spglib as spg

SpaceGroupIrep.wl
4669:  ExternalEvaluate[ss,"from spglib import *"];
```

![image](https://user-images.githubusercontent.com/11155854/153162046-549cf14d-86a1-4eb3-ad88-3a2b3ce7021e.png)

So, this will need a python environment where `spglib` is installed as a prerequisite. But this is not mentioned in the [README.md](https://github.com/goodluck1982/SpaceGroupIrep#readme). Therefore, I think it is best to add an appropriate additional explanation.

Regards,
HZ

**Comment by goodluck1982** [comment]
Thanks for your suggestion.  README.md has been updated.
