### ISSUE TITLE
Naming convention for the example `trace.txt` files in this project.

### ISSUE THREAD

**Issue by hongyi-zhao** [goodluck1982/SpaceGroupIrep#14]
Currently, there are the following example `trace.txt` files shipped with this project:
```
$ find . -type f -name '*trace.txt'
./examples/MoS2-S-center-trace.txt
./examples/SG205-trace.txt
./examples/MoS2-Mo-center-trace.txt
./examples/SG186-trace.txt
./examples/MoS2-h-center-trace.txt
```
Based on my understanding, I think there should be a general naming convention for these files. For example, the format I can think of is as follows:

`SGNumber-system_name-DFT_code-trace_generate_code-trace.txt`

Take `MoS2-S-center-trace.txt` as an example, it can be renamed into the following format:

`194-MoS2-S-center-VASP-vasp2trace-trace.txt` 

See [here](https://github.com/goodluck1982/SpaceGroupIrep/issues/5#issuecomment-1033554765) for a related discussion.

Regards,
HZ

**Comment by hongyi-zhao** [comment]
It may confuse users. A clear self-explanatory naming convention is a good habit.

**Comment by goodluck1982** [comment]
The intent of these trace files is not for users to explore them directly.  They are only example data files used by `document and examples.nb` and `test.nb`. Here they are only meaningful in the `.nb` files.

For example, the three MoS2 files, they are used in the `test.nb` file to show the codes in my paper
![图片](https://user-images.githubusercontent.com/48718961/153415752-eec5b43f-2d31-448b-96df-e98f29d52bfd.png)
Combined with `test.nb` and my paper, the meanings of the three files are clear. They correspond to three different cells.
![图片](https://user-images.githubusercontent.com/48718961/153417004-2e4060db-e46e-4d32-bf09-1c0f2c9fc781.png)

**Comment by hongyi-zhao** [comment]
I see. Thank you for your explanation.
